# Generated by Django 3.0.7 on 2020-07-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='featured1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='featured2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='featured3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p3', to='posts.post')),
            ],
        ),
        migrations.DeleteModel(
            name='homepage',
        ),
    ]
