# Generated by Django 3.0.7 on 2020-07-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200706_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured2',
            name='post1',
        ),
        migrations.RemoveField(
            model_name='featured3',
            name='post1',
        ),
        migrations.DeleteModel(
            name='featured1',
        ),
        migrations.DeleteModel(
            name='featured2',
        ),
        migrations.DeleteModel(
            name='featured3',
        ),
    ]
