# Generated by Django 3.0.7 on 2020-07-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200705_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='U_may_also_like_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option1', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='U_may_also_like_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option2', to='posts.post'),
        ),
    ]
