# Generated by Django 3.0.7 on 2020-07-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200712_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('key1', models.CharField(blank=True, max_length=50)),
                ('key2', models.CharField(blank=True, max_length=50)),
                ('key3', models.CharField(blank=True, max_length=50)),
                ('key4', models.CharField(blank=True, max_length=50)),
                ('key5', models.CharField(blank=True, max_length=50)),
                ('key6', models.CharField(blank=True, max_length=50)),
                ('key7', models.CharField(blank=True, max_length=50)),
                ('key8', models.CharField(blank=True, max_length=50)),
                ('key9', models.CharField(blank=True, max_length=50)),
                ('key10', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='key1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='key9',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
