# Generated by Django 3.0.7 on 2020-07-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200717_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='head',
            old_name='description',
            new_name='descriptions',
        ),
    ]
