# Generated by Django 3.0.7 on 2020-07-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200717_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='head',
        ),
    ]
